### ISSUE TITLE
运行完后报错 Failed to compile.

### ISSUE THREAD

**Issue by yang302** [superman66/react-douban#1]
Failed to compile.

Error in ./src/containers/movieList.js
Module not found: [CaseSensitivePathsPlugin] `D:\myCode\Demo\react-douban\src\reducers\movieList.js` does not match the corresponding path on disk `MovieList.js`.

 @ ./src/containers/movieList.js 23:18-50

**Comment by superman66** [comment]
多谢，已经修复了。你重新git pull 即可。
如果确认没问题的话，就可以把 issue 关了
